### ISSUE TITLE
The widget sets wrong label after midnight on that day's note when using a time with timezone on machine

### ISSUE THREAD

**Issue by admajewski** [Nriver/countdown-days-widget#1]
Hey! When its after midnight a journal page for today is saying that "There are 1 days left" instead of "Today!". The previous day one has label "Today!". 
Seems like dateNote value parsed into Date class gives a date with a timezone time included for example for "2024-04-14" is setting Sun Apr 14 2024 02:00:00 GMT+0200 (Central European Summer Time) which is causing this behaviour.

Potential fix:
* for note and current time it should always set midnight hours (for example using Date.setHour(0,0,0,0) ) before getting timestamp to properly count days

Thanks for nice script!

**Comment by Nriver** [comment]
Thank you for reporting this. I just made a fix here https://github.com/Nriver/countdown-days-widget/releases/tag/v1.0.1

**Comment by admajewski** [comment]
Thanks, will check it at night and close the issue if the fix helped!

**Comment by admajewski** [comment]
All good on my end, thanks again! :)

**Comment by felixovelar** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
CodeJunkiez, @apexo, @carina-akaia, @jsfour, @Anselem12, @adithya321, @Augustineebeke, @learningis1st, @vaibhav10107, @4zr0f4l, @augustodamasceno, @ncvv, @cagatay, @marconius, @chenjinlei1122, @bjimba, @AaronM04, @funkybase, @alexclaydon, @pavinan, @kevinfudan, @nosscafe66, @yqrashawn, @khwilo, @xxtarhxx, @ultimate255, @MrsAzhar, @hmisty, @AntoniosHadji, @pomoq-dev, @sahil-byte, @langest, @nwiizo, @Urban-Ash, @romanz, @gwn, @safronizator, @draculaas, @RDMEC, @t4t5, @yubozhao, @Amolrada2442, @arnezami, @jonwho, @saeedahadian, @FcknPerfect, @fractalshine, @tajik225, @AlyAbdou, @bagher2901
